PackageIdentifier: dkmcgowan.finzy
PackageVersion: 0.1.7
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
UpgradeBehavior: install
ReleaseNotesUrl: https://github.com/dkmcgowan/finzy/releases
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/dkmcgowan/finzy/releases/download/0.1.7/finzy-windows-installer.exe
    InstallerSha256: 06433291a1e7adb3b0b21bda5f0085b02939a00e419ac6de59beaef27e6fb856
    InstallerSwitches:
      Silent: /VERYSILENT
      SilentWithProgress: /SILENT
  - Architecture: arm64
    InstallerUrl: https://github.com/dkmcgowan/finzy/releases/download/0.1.7/finzy-windows-installer.exe
    InstallerSha256: 06433291a1e7adb3b0b21bda5f0085b02939a00e419ac6de59beaef27e6fb856
    InstallerSwitches:
      Silent: /VERYSILENT
      SilentWithProgress: /SILENT
ManifestType: installer
ManifestVersion: 1.6.0