PackageIdentifier: dkmcgowan.finzy
PackageVersion: 0.1.8
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
UpgradeBehavior: install
ReleaseNotesUrl: https://github.com/dkmcgowan/finzy/releases
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/dkmcgowan/finzy/releases/download/0.1.8/finzy-windows-installer.exe
    InstallerSha256: a3baa2dddb8094e466f912801ff56d4b9f3db9705c6f061f432b12cfdbcf0837
    InstallerSwitches:
      Silent: /VERYSILENT
      SilentWithProgress: /SILENT
  - Architecture: arm64
    InstallerUrl: https://github.com/dkmcgowan/finzy/releases/download/0.1.8/finzy-windows-installer.exe
    InstallerSha256: a3baa2dddb8094e466f912801ff56d4b9f3db9705c6f061f432b12cfdbcf0837
    InstallerSwitches:
      Silent: /VERYSILENT
      SilentWithProgress: /SILENT
ManifestType: installer
ManifestVersion: 1.6.0